### ISSUE TITLE
Instructions needed for the layperson

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe-rich-text-merge-tags#3]
This should include instructions in the merge tags settings, explaining what this is. I see other services do use the term "merge tags" but it's the first I've heard it. People coming from Word as their text editing experience might be totally unfamiliar with the concept.

Something like:
> Merge tags are bits of text that you can reuse and reference in any rich text editor configured for them. Add a merge tag and its text value here, then look for the puzzle piece icon in the toolbar of your rich text editor to place the merge tag. If you later edit the text value here, the change will take effect everywhere the merge tag has been placed.

It should be able to use the `{% block instructions %}{% endblock %}` in the modal.

**Comment by boutell** [comment]
Thanks. I added this to the README, and added more background to the help text for the fields. Programmatically accessing the instructions block of the existing "global doc" modal, or better yet introducing help text on a per-tab basis, is a great idea but out of scope for this module's first release IMHO.
