### ISSUE TITLE
Adding JS to the merge tag value throws error but doesn't reject or cleanly filter out the tag

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe-rich-text-merge-tags#4]
I edited an existing merge tag to `Hey<script>alert('hackers');</script>`. On saving, the text on the page did not change and there's a console error: `TypeError: apos.entityMap is undefined` pointing to:
https://github.com/apostrophecms/apostrophe-rich-text-merge-tags/blob/master/public/js/user.js#L15

Opening the merge tags editing modal shows that my hacker script is still there, still saves, and the old text value still shows on the page. I think we should either filter out the script tags and output whatever is left, or make the save fail and display a client error.

**Comment by abea** [comment]
If a create a new tag with my hacker script, it does output the `**MISSING**` value, but in both cases it breaks most of the client-side JS on the page.

This all still happens with the less malicious `Hey <span>test</span>`.

**Comment by boutell** [comment]
apos.utils.escapeHtml didn't work browser side in Apostrophe since.... 2.0.0. 😢 Will be fixed in the release that coincides with this module's release.
